<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        $user =
            [
            'username' => 'admin',
            'email' => 'admin@gmail.com',
            'password' => bcrypt('12345678'),
            'created_at' => now(),
            'updated_at' => now(),
        ];

        $pendapatan =

            [
            [
                "Bulan" => "Januari",
                "Tahun" => "2021",
                "Pendapatan" => "11520000",
            ],
            [
                "Bulan" => "Febuari",
                "Tahun" => "2021",
                "Pendapatan" => "11290000",
            ],
            [
                "Bulan" => "Maret",
                "Tahun" => "2021",
                "Pendapatan" => "20100000",
            ],
            [
                "Bulan" => "April ",
                "Tahun" => "2021",
                "Pendapatan" => "12400000",
            ],
            [
                "Bulan" => "Mei ",
                "Tahun" => "2021",
                "Pendapatan" => "26700000",
            ],
            [
                "Bulan" => "Juni",
                "Tahun" => "2021",
                "Pendapatan" => "12860000",
            ],
            [
                "Bulan" => "Juli",
                "Tahun" => "2021",
                "Pendapatan" => "18100000",
            ],
            [
                "Bulan" => "Agustus",
                "Tahun" => "2021",
                "Pendapatan" => "10200000",
            ],
            [
                "Bulan" => "September",
                "Tahun" => "2021",
                "Pendapatan" => "18650000",
            ],
            [
                "Bulan" => "Oktober",
                "Tahun" => "2021",
                "Pendapatan" => "11670000",
            ],
            [
                "Bulan" => "November ",
                "Tahun" => "2021",
                "Pendapatan" => "29000000",
            ],
            [
                "Bulan" => "Desember",
                "Tahun" => "2021",
                "Pendapatan" => "27980000",
            ],
            [
                "Bulan" => "Januari",
                "Tahun" => "2022",
                "Pendapatan" => "28400000",
            ],
            [
                "Bulan" => "Febuari",
                "Tahun" => "2022",
                "Pendapatan" => "8160000",
            ],
            [
                "Bulan" => "Maret",
                "Tahun" => "2022",
                "Pendapatan" => "22800000",
            ],
            [
                "Bulan" => "April ",
                "Tahun" => "2022",
                "Pendapatan" => "15160000",
            ],
            [
                "Bulan" => "Mei ",
                "Tahun" => "2022",
                "Pendapatan" => "13220000",
            ],
            [
                "Bulan" => "Juni",
                "Tahun" => "2022",
                "Pendapatan" => "31000000",
            ],
            [
                "Bulan" => "Juli",
                "Tahun" => "2022",
                "Pendapatan" => "26330000",
            ],
            [
                "Bulan" => "Agustus",
                "Tahun" => "2022",
                "Pendapatan" => "13810000",
            ],
            [
                "Bulan" => "September",
                "Tahun" => "2022",
                "Pendapatan" => "5560000",
            ],
            [
                "Bulan" => "Oktober",
                "Tahun" => "2022",
                "Pendapatan" => "10920000",
            ],
            [
                "Bulan" => "November ",
                "Tahun" => "2022",
                "Pendapatan" => "7500000",
            ],
            [
                "Bulan" => "Desember",
                "Tahun" => "2022",
                "Pendapatan" => "25050000",
            ],

        ];

        $detailpendapatan = 
            [
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "S",
                    "warna"=> "Merah ",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1225000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "27",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "945000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 22,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "770000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "XL",
                    "warna"=> "Hijau",
                    "penjualan"=> 18,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "630000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "800000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "S",
                    "warna"=> "Merah ",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "900000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "41",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1845000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1575000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> 21,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1080000",
               ],
               [
                    "pendapatan_id"=> 1,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1750000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "S",
                    "warna"=> "Merah ",
                    "penjualan"=> 24,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1020000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "32",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1120000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "27",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1080000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "51",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1785000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "73",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1560000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1700000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "27",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "915000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "42",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "890000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "66",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "970000",
               ],
               [
                    "pendapatan_id"=>2,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "65",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "250000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1420000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 14,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "490000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 24,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "840000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 12,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1420000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> 19,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1760000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> 16,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1720000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 18,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "8100000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 5,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2250000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "2",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "900000",
               ],
               [
                    "pendapatan_id"=> 3,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> 4,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1200000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "700000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 19,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "665000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 11,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "385000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1145000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> 9,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1360000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> 23,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1035000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 22,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1990000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 21,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1945000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> 15,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1675000",
               ],
               [
                    "pendapatan_id"=> 4,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> 10,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1500000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "100",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3500000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "55",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1925000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "68",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2380000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "55",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1925000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1200000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "100",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "4500000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "67",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "3015000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "68",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "3080000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "55",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2475000",
               ],
               [
                    "pendapatan_id"=> 5,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "54",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2700000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 10,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "625000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 19,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "665000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "700000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 21,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1735000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1200000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> 23,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1035000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "29",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1305000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 22,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1990000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> 19,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1855000",
               ],
               [
                    "pendapatan_id"=> 6,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> 15,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1750000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "40",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1400000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "55",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1925000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "45",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1575000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "59",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2065000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "54",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2160000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "54",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2430000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "34",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1340000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "59",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1655000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "40",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1800000",
               ],
               [
                    "pendapatan_id"=> 7,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "55",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1750000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "66",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2310000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "70",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1450000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "61",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1135000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "70",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1450000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "41",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1640000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "85",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "535000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "70",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "250000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "80",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "600000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "34",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "530000",
               ],
               [
                    "pendapatan_id"=> 8,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "300000",
               ],
               
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 22,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1770000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 21,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1735000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "28",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1980000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 23,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1805000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "25",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1000000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "25",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1125000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "28",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1260000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "28",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2260000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "43",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2935000",
               ],
               [
                    "pendapatan_id"=> 9,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "50",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2780000",
               ],
               
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "46",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1610000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "32",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1120000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "39",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1365000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1050000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "33",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1320000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "47",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1210000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "33",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1485000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "45",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1025000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "43",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "935000",
               ],
               [
                    "pendapatan_id"=> 10,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "31",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "550000",
               ],
               
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2700000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "36",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2260000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "38",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2330000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2050000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "4200000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "39",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2755000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2900000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2575000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "4230000",
               ],
               [
                    "pendapatan_id"=> 11,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "40",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "3000000",
               ],
               
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 24,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2840000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "25",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3875000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 16,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3560000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "31",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1085000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> 16,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2640000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "28",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1260000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 13,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "3585000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 19,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "4855000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "28",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2260000",
               ],
               [
                    "pendapatan_id"=> 12,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> 22,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2020000",
               ],
               
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "S",
                    "warna"=> "Merah ",
                    "penjualan"=> "41",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3435000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2050000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "31",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2085000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "XL",
                    "warna"=> "Hijau",
                    "penjualan"=> "49",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2715000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "26",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2040000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "S",
                    "warna"=> "Merah ",
                    "penjualan"=> "43",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2200000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "43",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1935000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "57",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "3565000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "65",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "3925000",
               ],
               [
                    "pendapatan_id"=> 13,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "49",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "4450000",
               ],
               
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "S",
                    "warna"=> "Merah ",
                    "penjualan"=> 24,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "840000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "25",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "875000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 10,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "350000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 16,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "560000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> 23,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "920000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> 22,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "990000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "29",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1305000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 10,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "450000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> 15,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "675000",
               ],
               [
                    "pendapatan_id"=> 14,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> 10,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1195000",
               ],
               
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 5,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3175000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 7,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1245000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 14,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2490000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 9,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1315000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> 9,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1765000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> 10,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1450000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 15,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "4675000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 11,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "3495000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> 12,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1540000",
               ],
               [
                    "pendapatan_id"=> 15,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> 13,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1650000",
               ],
               
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1465000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 21,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "735000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1700000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "29",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1015000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> 24,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1960000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "25",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1125000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 9,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2405000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 15,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1675000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> 14,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1630000",
               ],
               [
                    "pendapatan_id"=> 16,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "29",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1450000",
               ],
               
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> 21,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1060000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 18,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "930000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 19,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "965000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 24,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1840000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1200000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> 22,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1990000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "26",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1170000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 22,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1990000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "25",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1125000",
               ],
               [
                    "pendapatan_id"=> 17,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> 19,
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "950000",
               ],
               
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "46",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "4610000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3050000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3050000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "50",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3750000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "41",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3640000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "42",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2890000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2575000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "45",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2025000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "36",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2620000",
               ],
               [
                    "pendapatan_id"=> 18,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "37",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2790000",
               ],
               
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3100000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "26",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3040000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "51",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2785000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "44",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2540000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2400000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "47",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2115000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "43",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2935000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "57",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2565000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2700000",
               ],
               [
                    "pendapatan_id"=> 19,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "43",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2150000",
               ],
               
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "75",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1625000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1100000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "70",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1450000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1100000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1400000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "51",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1295000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "80",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1600000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "70",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1150000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1700000",
               ],
               [
                    "pendapatan_id"=> 20,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "70",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1390000",
               ],
               
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "500000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "38",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "330000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "39",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "365000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "32",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "600000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "200000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "38",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "710000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "36",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "620000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "575000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "38",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "710000",
               ],
               [
                    "pendapatan_id"=> 21,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "40",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "950000",
               ],
               
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "33",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1155000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 20,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "700000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "55",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "925000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> "70",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1450000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "830000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "42",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "890000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "32",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1440000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "54",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1430000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "80",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1600000",
               ],
               [
                    "pendapatan_id"=> 22,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "60",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "500000",
               ],
               
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "29",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1015000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> 23,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "805000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1225000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 24,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "840000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "36",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1440000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "53",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "385000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "30",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "350000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "58",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "610000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "51",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "360000",
               ],
               [
                    "pendapatan_id"=> 23,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "52",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "470000",
               ],
               
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "S",
                    "warna"=> "Kuning ",
                    "penjualan"=> "36",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "2260000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "36",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1825000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> 24,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3840000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "XL",
                    "warna"=> "Maron",
                    "penjualan"=> 21,
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "3735000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "XXL",
                    "warna"=> "Putih",
                    "penjualan"=> "46",
                    "jenis_kaos"=> "Pendek",
                    "pendapatan"=> "1840000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "S",
                    "warna"=> "Navy",
                    "penjualan"=> "48",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2160000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "M",
                    "warna"=> "Hitam ",
                    "penjualan"=> "47",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2115000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "L",
                    "warna"=> "Biru",
                    "penjualan"=> "35",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "1575000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "XL",
                    "warna"=> "Abu-abu",
                    "penjualan"=> "40",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2800000",
               ],
               [
                    "pendapatan_id"=> 24,
                    "ukuran"=> "XXL",
                    "warna"=> "Hitam ",
                    "penjualan"=> "38",
                    "jenis_kaos"=> "Panjang",
                    "pendapatan"=> "2900000",
               ]
        ];
        

        DB::table('users')->insert($user);
        DB::table('pendapatans')->insert($pendapatan);
        DB::table('detail_pendapatans')->insert($detailpendapatan);
    }
}
